---
apiVersion: v1
kind: Service
metadata:
  name: notificationapp-svc
spec:
  ports:
  - port: 9001
    targetPort: myapp-port
    protocol: TCP
  selector:
    app: notificationapp-webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notificationappdeployment
  labels:
    app: notificationapp-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notificationapp-webapp
  template:
    metadata:
      labels:
        app: notificationapp-webapp
    spec:
      containers:
      - name: notificationapp
        image: gaje85/notificationapp
        imagePullPolicy: IfNotPresent
        ports:
        - name: myapp-port
          containerPort: 9001
