---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app.kubernetes.io/name: "ui-svc"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "ui-svc"
---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "https://github.com/gaje85/kubernetessampleapp.git"
    app.dekorate.io/commit-id: "83cba22a9a4242861c76851ca53f8e5ebbe6f05f"
  labels:
    app.kubernetes.io/name: "ui-svc"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "ui-svc"
spec:
  ports:
  - name: "http"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/name: "ui-svc"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  type: "ClusterIP"
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  labels:
    app.kubernetes.io/name: "ui-svc"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "ui-svc:view"
roleRef:
  kind: "ClusterRole"
  apiGroup: "rbac.authorization.k8s.io"
  name: "view"
subjects:
- kind: "ServiceAccount"
  name: "ui-svc"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.dekorate.io/vcs-url: "https://github.com/gaje85/kubernetessampleapp.git"
    app.dekorate.io/commit-id: "83cba22a9a4242861c76851ca53f8e5ebbe6f05f"
  labels:
    app.kubernetes.io/name: "ui-svc"
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  name: "ui-svc"
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: "ui-svc"
      app.kubernetes.io/version: "0.0.1-SNAPSHOT"
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: "https://github.com/gaje85/kubernetessampleapp.git"
        app.dekorate.io/commit-id: "83cba22a9a4242861c76851ca53f8e5ebbe6f05f"
      labels:
        app.kubernetes.io/name: "ui-svc"
        app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "gaje85/ui"
        imagePullPolicy: "Always"
        name: "ui"
        resources:
          requests:
            memory: "1024M"
            cpu: "500m"
          limits:
            memory: "1560M"
            cpu: "800m"
        ports:
        - containerPort: 3001
          name: "http"
          protocol: "TCP"
      serviceAccount: "ui-svc"
