---
apiVersion: v1
kind: Service
metadata:
  name: devopstracker-svc
spec:
  ports:
  - port: 9000
    targetPort: myapp-port
    protocol: TCP
  selector:
    app: devopstracker-webapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstrackerdeployment
  labels:
    app: devopstracker-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devopstracker-webapp
  template:
    metadata:
      labels:
        app: devopstracker-webapp
    spec:
      containers:
      - name: devopstracker
        image: gaje85/devopstrackerapi
        imagePullPolicy: IfNotPresent
        ports:
        - name: myapp-port
          containerPort: 9000
